version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "devops-app-repo"
    IMAGE_TAG: "latest"
    AWS_REGION: "us-east-1"

phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - set -e
      - echo Logging in to Amazon ECR...
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - echo "Account ID is $ACCOUNT_ID"
      - |
        if [ "$ACCOUNT_ID" = "None" ] || [ -z "$ACCOUNT_ID" ]; then
          echo "ERROR: Failed to get Account ID"
          exit 1
        fi
      - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - echo "ECR Repo URI:$REPOSITORY_URI"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI

      - echo Making Python scripts executable...
      - chmod +x scripts/*.py

      - echo Installing Terraform...
      - curl -LO https://releases.hashicorp.com/terraform/1.8.5/terraform_1.8.5_linux_amd64.zip
      - unzip -o terraform_1.8.5_linux_amd64.zip -d /tmp
      - mv /tmp/terraform /usr/local/bin/
      - terraform version

      - echo Fetching Infracost API Key from SSM...
      - INFRACOST_API_KEY=$(aws ssm get-parameter --name "/infracost/api_key" --with-decryption --query "Parameter.Value" --output text)
      - export INFRACOST_API_KEY
      - echo "Infracost API Key fetched successfully"


      - echo Installing Infracost...
      - curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
      - infracost --version

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $IMAGE_REPO_NAME ./flask_web_app/app
      - "docker tag $IMAGE_REPO_NAME:latest $REPOSITORY_URI:$IMAGE_TAG"
      - echo Pushing Docker image to ECR...
      - "docker push $REPOSITORY_URI:$IMAGE_TAG"

      - echo Running Terraform...
      - cd terraform
      - terraform init
      - terraform plan -out=tfplan.binary
      - terraform show -json tfplan.binary > plan.json
      # - terraform apply -auto-approve tfplan.binary

      - echo Running Infracost cost estimation...
      - infracost breakdown --path=plan.json --format table

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - appspec.yml
    - buildspec-apply.yml
    - scripts/**/*
    - terraform/**/*